### DISCUSSION TITLE
Self Hosted compose.yml Is Missing ENV File Documentation

### DISCUSSION THREAD

**Discussion by epoch-philosophy** [bluesky-social/pds#132] [General]
Was wondering if I am missing something, but the compose.yml file in the PDS service references an ENV file. Yet, the documentation doesn't contain necessary environment variables or the potential ENV file that needs to be attatched to the container.

```
pds:
  container_name: pds
  image: ghcr.io/bluesky-social/pds:0.4
  network_mode: host
  restart: unless-stopped
  volumes:
    - type: bind
       source: /pds
       target: /pds
  env_file:
      - /pds/pds.env
```
        
Could anyone be of help with this?
