### ISSUE TITLE
Failure to launch the container

### ISSUE THREAD

**Issue by mstarongithub** [bluesky-social/pds#109]
Every time I try to launch the container via docker, I end up getting this exact error message multiple times:

```
Attaching to bsky-1
bsky-1  | /app/node_modules/.pnpm/multiformats@9.9.0/node_modules/multiformats/cjs/src/bases/base.js:119
bsky-1  |     throw new SyntaxError('Unexpected end of data');
bsky-1  |           ^
bsky-1  |
bsky-1  | SyntaxError: Unexpected end of data
bsky-1  |     at decode (/app/node_modules/.pnpm/multiformats@9.9.0/node_modules/multiformats/cjs/src/bases/base.js:119:11)
bsky-1  |     at Decoder.decode [as baseDecode] (/app/node_modules/.pnpm/multiformats@9.9.0/node_modules/multiformats/cjs/src/bases/base.js:155:14)
bsky-1  |     at Decoder.decode (/app/node_modules/.pnpm/multiformats@9.9.0/node_modules/multiformats/cjs/src/bases/base.js:37:19)
bsky-1  |     at fromString (/app/node_modules/.pnpm/uint8arrays@3.0.0/node_modules/uint8arrays/cjs/src/from-string.js:12:23)
bsky-1  |     at Function.import (/app/node_modules/.pnpm/@atproto+crypto@0.4.1/node_modules/@atproto/crypto/src/secp256k1/keypair.ts:42:50)
bsky-1  |     at Function.fromConfig (/app/node_modules/.pnpm/@atproto+pds@0.4.59/node_modules/@atproto/pds/src/context.ts:242:47)
bsky-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bsky-1  |     at Function.create (/app/node_modules/.pnpm/@atproto+pds@0.4.59/node_modules/@atproto/pds/src/index.ts:57:17)
bsky-1  |     at async main (/app/index.js:16:15)
bsky-1  |
bsky-1  | Node.js v20.11.1
bsky-1 exited with code 0
```

I tried it with the `latest`, `0.4` and `sha-f07a20e7e8e3b60eb40fbf735cabda8cd6a0e9d2` (the latest build as of right now).

My docker-compose file is as follows:

```
services:
  bsky:
    image: ghcr.io/bluesky-social/pds:latest
    restart: unless-stopped
    volumes:
      - "./pds:/pds"
    env_file:
      - ./pds/pds.env
    # environment:
    #   PDS_HOSTNAME: bsky.***.***
    #   PDS_JWT_SECRET: ***
    #   PDS_ADMIN_PASSWORD: ***
    #   PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ***
    #   PDS_DATADIR: /pds
    #   PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
    #   PDS_BLOB_UPLOAD_LIMIT: 52428800
    #   PDS_DID_PLC_URL: https://plc.directory
    #   PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
    #   PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
    #   PDS_REPORT_SERVICE_URL: https://mod.bsky.app
    #   PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
    #   PDS_CRAWLERS: https://bsky.network
    #   LOG_ENABLED: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bsky.rule=Host(`bsky.***.***`)||HostRegexp(`^.+\\.bsky\.***\\.***$`)"
      - "traefik.http.routers.bsky.entrypoints=websecure"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - public

networks:
  public:
    external: true
```
The environment file contains the exact same entries as the (currently commented out) `environment` section.
Docker itself is at version `Docker version 27.3.1, build ce1223` and Compose at version `Docker Compose version v2.29.7`
