### ISSUE TITLE
Self-contained Docker Image

### ISSUE THREAD

**Issue by gravityfargo** [bluesky-social/pds#175]
I posted this in the Discord, but I'll post here as well. I made a self contained docker container that works behind traefik with some instructions. I've run through the deployment I documented a few times and resulted in a functional pds each time. I made this for another project, but I figured others would find it useful.
Repo:
https://forgejo.gravityfargo.dev/gravityfargo/bluesky-pds-docker
Container:
https://forgejo.gravityfargo.dev/gravityfargo/-/packages/container/bluesky-pds/latest

```yaml
services:
  bluesky-pds:
    container_name: bluesky-pds
    image: forgejo.gravityfargo.dev/gravityfargo/bluesky-pds:latest
    networks:
      - proxy
    env_file:
      PDS_ADMIN_PASSWORD: ""
      PDS_JWT_SECRET: ""
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ""
      PDS_HOSTNAME: example.com
      PDS_EMAIL_SMTP_URL: ""
      PDS_EMAIL_FROM_ADDRESS: ""
    volumes:
      - ./bluesky-pds:/pds
    labels:
      traefik.enable: "true"
      traefik.http.routers.bluesky-pds-insecure.entrypoints: http
      traefik.http.routers.bluesky-pds-insecure.rule: HostRegexp(`^.+\.example\.com$`) || Host(`example.social`)
      traefik.http.routers.bluesky-pds-secure.entrypoints: https
      traefik.http.routers.bluesky-pds-secure.rule: HostRegexp(`^.+\.example\.com$`) || Host(`example.social`)
      traefik.http.routers.bluesky-pds-secure.tls: "true"
      traefik.http.services.bluesky-pds.loadbalancer.server.scheme: http
      traefik.http.services.bluesky-pds.loadbalancer.server.port: 3000
```
