### ISSUE TITLE
Cannot see any feed

### ISSUE THREAD

**Issue by CyberPingU** [bluesky-social/pds#26]
Hello,
my steup is with docker

nginx on dmz server<--> port 3000 of pds into internal network

I removed caddy:
```
version: '3.9'
services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds
        target: /pds
    env_file:
      - /pds/pds.env
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "@midnight"
```
So the nginx is reverse proxying to pds directly.

```
  upstream home {
    server 192.168.253.3:3000;
    keepalive 15;
  }

server {
    server_name home.REDACTED.eu;
    server_name *.home.REDACTED.eu;

    location / {
#      auth_basic "Restricted Access";
#      auth_basic_user_file /etc/nginx/htpasswd.users;

add_header                X-ECache 1;
  add_header                X-ECache-Key    $host$uri$is_args$args;
  add_header                X-ECache-Status $upstream_cache_status;
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  proxy_ignore_headers      "Expires";
  proxy_ignore_headers      "Cache-Control";

  proxy_cache_key           "$host$uri$is_args$args";
  proxy_cache_valid         200 1d;

      proxy_pass http://home;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;    
      proxy_redirect off;
      proxy_buffering off;

      proxy_set_header Connection "Keep-Alive";
      proxy_set_header Proxy-Connection "Keep-Alive";
 client_max_body_size 10G;
client_body_buffer_size 400M;
    }
   listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/home.REDACTED.eu/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/home.REDACTED.eu/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
location /.well-known/carddav {
    return 301 $scheme://$host/remote.php/dav;
}

location /.well-known/caldav {
    return 301 $scheme://$host/remote.php/dav;
}
}
server {
    if ($host = home.REDACTED.eu) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name home.REDACTED.eu;
    listen 80;
    return 404; # managed by Certbot
}
```
I used letsencrypt to generate a wildcard to *.home.REDACTED.eu

I can login, see profile and such, but my feed is empty.

Where am I mistaken?
